name: Deploy WordPress on Windows

on:
  push:
    branches:
      - main

jobs:
  deploy-wordpress:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install required software
      run: |
        choco install -y mysql php php-cgi wordpress
        setx PATH "%PATH%;C:\Program Files\MySQL\MySQL Server 8.0\bin"
        setx PATH "%PATH%;C:\tools\php"

    - name: Configure MySQL
      run: |
        net start MySQL80
        mysqladmin -u root password "123456"
        mysql -u root -p123456 -e "CREATE DATABASE wordpress;"
        mysql -u root -p123456 -e "CREATE USER 'wp_user'@'localhost' IDENTIFIED BY 'password';"
        mysql -u root -p123456 -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wp_user'@'localhost';"
        mysql -u root -p123456 -e "FLUSH PRIVILEGES;"
    - name: Download and set up WordPress
      run: |
        # Tải WordPress
        curl -o wordpress.zip https://wordpress.org/latest.zip
        mkdir C:\wordpress
        tar -xf wordpress.zip -C C:\wordpress --strip-components=1

        # Sao chép WordPress vào thư mục web
        mkdir C:\inetpub\wwwroot\wordpress
        xcopy "C:\wordpress\*" "C:\inetpub\wwwroot\wordpress" /E /I /Q /Y

        # Cấu hình WordPress
        copy "C:\inetpub\wwwroot\wordpress\wp-config-sample.php" "C:\inetpub\wwwroot\wordpress\wp-config.php"
        powershell -Command "(Get-Content C:\inetpub\wwwroot\wordpress\wp-config.php).Replace('database_name_here', 'wordpress') | Set-Content C:\inetpub\wwwroot\wordpress\wp-config.php"
        powershell -Command "(Get-Content C:\inetpub\wwwroot\wordpress\wp-config.php).Replace('username_here', 'wp_user') | Set-Content C:\inetpub\wwwroot\wordpress\wp-config.php"
        powershell -Command "(Get-Content C:\inetpub\wwwroot\wordpress\wp-config.php).Replace('password_here', 'password') | Set-Content C:\inetpub\wwwroot\wordpress\wp-config.php"

    - name: Set up WordPress
      run: |
        mkdir C:\inetpub\wwwroot\wordpress
        xcopy "C:\tools\wordpress\*" "C:\inetpub\wwwroot\wordpress" /E /I /Q /Y
        copy "C:\inetpub\wwwroot\wordpress\wp-config-sample.php" "C:\inetpub\wwwroot\wordpress\wp-config.php"
        powershell -Command "(Get-Content C:\inetpub\wwwroot\wordpress\wp-config.php).Replace('database_name_here', 'wordpress') | Set-Content C:\inetpub\wwwroot\wordpress\wp-config.php"
        powershell -Command "(Get-Content C:\inetpub\wwwroot\wordpress\wp-config.php).Replace('username_here', 'wp_user') | Set-Content C:\inetpub\wwwroot\wordpress\wp-config.php"
        powershell -Command "(Get-Content C:\inetpub\wwwroot\wordpress\wp-config.php).Replace('password_here', 'password') | Set-Content C:\inetpub\wwwroot\wordpress\wp-config.php"

    - name: Install Quick Tunnel (Cloudflare Tunnel)
      run: |
        curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -o cloudflared.exe
        start /b cloudflared.exe tunnel --url http://localhost:80 > tunnel.log 2>&1
        timeout /t 5
        FOR /F "tokens=*" %i IN ('findstr "https://" tunnel.log') DO @echo Quick Tunnel URL: %i

    - name: Set up "Hello World" Page
      run: |
        echo "<?php echo 'Hello World'; ?>" > C:\inetpub\wwwroot\wordpress\index.php
        echo '<a href="/wp-login.php">Login as Admin</a>' >> C:\inetpub\wwwroot\wordpress\index.php
        echo "<p>Admin Username: <b>admin</b></p>" >> C:\inetpub\wwwroot\wordpress\index.php
        echo "<p>Admin Password: <b>admin</b></p>" >> C:\inetpub\wwwroot\wordpress\index.php
