name: Deploy WordPress with Quick Tunnel

on:
  push:
    branches:
      - main

jobs:
  deploy-wordpress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install required packages
      run: |
        sudo apt update
        sudo apt install -y apache2 php php-mysql mysql-server unzip wget
        sudo systemctl start apache2
        sudo systemctl enable apache2

    - name: Set up MySQL
      run: |
        # Khởi động MySQL dưới quyền root
        sudo systemctl start mysql
        sudo systemctl enable mysql

        # Đặt mật khẩu root mặc định là '123456'
        sudo mysql --user=root <<-EOSQL
          ALTER USER 'root'@'localhost' IDENTIFIED BY '123456';
          FLUSH PRIVILEGES;
        EOSQL

        # Sử dụng mật khẩu root để tạo database và user
        sudo mysql --user=root --password=123456 <<-EOSQL
          CREATE DATABASE wordpress;
          CREATE USER 'wp_user'@'localhost' IDENTIFIED BY 'password';
          GRANT ALL PRIVILEGES ON wordpress.* TO 'wp_user'@'localhost';
          FLUSH PRIVILEGES;
        EOSQL



    - name: Download and install WordPress
      run: |
        wget https://wordpress.org/latest.zip
        unzip latest.zip
        sudo mv wordpress/* /var/www/html/
        sudo chown -R www-data:www-data /var/www/html
        sudo chmod -R 755 /var/www/html

        # Configure WordPress
        cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
        sed -i "s/database_name_here/wordpress/" /var/www/html/wp-config.php
        sed -i "s/username_here/wp_user/" /var/www/html/wp-config.php
        sed -i "s/password_here/password/" /var/www/html/wp-config.php

    - name: Install Cloudflare Tunnel
      run: |
        curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
        sudo mv cloudflared /usr/local/bin
        sudo chmod +x /usr/local/bin/cloudflared

    - name: Start Quick Tunnel
      run: |
        nohup cloudflared tunnel --url http://localhost &> tunnel.log &
        sleep 5
        TUNNEL_URL=$(grep -o 'https://[^ ]*' tunnel.log | head -1)
        echo "TUNNEL_URL=$TUNNEL_URL" >> $GITHUB_ENV

    - name: Configure WordPress "Hello World" page
      run: |
        echo "<?php echo 'Hello World'; ?>" > /var/www/html/index.php
        echo '<a href="/wp-login.php">Login as Admin</a>' >> /var/www/html/index.php
        echo "<p>Admin Username: <b>admin</b></p>" >> /var/www/html/index.php
        echo "<p>Admin Password: <b>admin</b></p>" >> /var/www/html/index.php

    - name: Display Quick Tunnel URL
      run: |
        echo "Access your WordPress site at: ${{ env.TUNNEL_URL }}"
